### ISSUE TITLE
DB integration

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#146]
### Description
As an alternative to storing many of the file formats (e.g., FeatureXML, TraML, etc.,) as individual .xml or .csv files, it maybe more convenient for downstream processing to store the file formats in a persistent SQL compliant format that could then be queried for down stream processing and analysis.

### Objectives
- [ ] minimal support for connecting to SQLite and submitting raw string transactions against the database
- [ ] similar support for other databases (e.g., postgres)
- [ ] negligible ORM support; users will need to interact with the database using raw SQL string syntax
- [ ] Schemas for our most utilized file formats that are most ameniable to SQL storage (i.e., probably not mzML)

### Links
- see https://github.com/OpenMS/OpenMS/issues/3371
