### ISSUE TITLE
SmartPeak validation experiments

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#163]
### Description
In silico validation experiments required for publication of the new SmartPeak data processing algorithms

### Objectives
1. MRMFeatureSelector validation experiments using LC-MS, HPLC, GC-MS, and CE-MS data
2. EMG fitting validation experiments on LC-MS calibrators and QCs
3. Example LC-MS and HPLC data set using AbsoluteQuantitation
4. Example LC-MS data using MRMFeatureFilter and MRMFeatureQC
5. Example LC-MS and GC-MS data set using the TargetedSpectrumExtractor workflow

**Comment by pcolaianni** [comment]
When proposing the targeted/untargeted methods PR to OpenMS, I made the following change in `selectSpectra()`: replaced `unordered_map` with `map`.

During the validation tests, we should check if such change provokes a performance regression.

The only advantage of using `map` is that users will have the extracted spectra sorted in the same order, no matter what platform (win, mac, linux) they work on.

**Comment by dmccloskey** [comment]
### Notes on data collection for validation experiments:
**MRMFeatureSelector validation experiments using LC-MS, HPLC, GC-MS, and CE-MS data**
- [x] Dump manually integrated peak data from DB (LC-MS)
- [x] Ensure all raw data files have been converted to MzML (LC-MS)
- [ ] Clean up/organize example data for HPLC, GC-MS, and CE-MS 
- [ ] Run LC-MS quantitation examples
- [ ] Run LC-MS fluxomic examples
**EMG fitting validation experiments on LC-MS calibrators and QCs**
- [ ] Identify saturated compounds for calibrator example
- [ ] Identify cutoff compounds for QC example
**Example LC-MS and HPLC data set using AbsoluteQuantitation**
- [x] Dump calibration curve fit statistics from DB (LC-MS)
**Example LC-MS data using MRMFeatureFilter and MRMFeatureQC**
- [x] Figure of examples and scoring metric
**Example LC-MS and GC-MS data set using the TargetedSpectrumExtractor workflow**
- [x] Dump manually processed isotopomer data from DB (LC-MS)
- [ ] NIST example
- [ ] LC-MS/MS DDA example?
