### ISSUE TITLE
Advanced graph/plotting module with ImGui

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#164]
### Description
C++ Open- [ ]source support for advanced graphing/plotting that can be natively integrated with the SmartPeak pipelines.

### Objectives (low level plotting features)
Low level plotting features utilized in both plots and layouts
- [x] scales
- [x] axes
- [ ] color bars
- [x] legend
- [x] error bars
- [x] labels

### Objectives (interactivity)
- [ ] data filtering
- [ ] tooltip and hovering
- [ ] zoom
- [ ] pan

### Objectives (higher level plotting features)
Basic and advanced plotting and layout functions

##### Basics
- [x] Line
- [x] Scatter
- [x] Bar (stacked)
- [x] Barh
- [ ] BoxPlot
- [x] Pie
- [x] Area (stacked)
- [ ] Heatmap
- [ ] Histogram (density and binning)

##### Advanced
- [ ] Contour
- [ ] Stem
- [ ] Stream
- [ ] Polar
- [ ] Radar
- [ ] Hexagonal binning
- [ ] Histogram 2D
- [ ] Violin
- [ ] Joint
- [ ] Strip
- [ ] Swarm

#### Layouts and hierarchies
- [ ] circos layout
- [ ] swim lanes
- [ ] bundle diagram
- [ ] chord diagram
- [ ] force directed graph
- [ ] force layout
- [ ] indented tree layout
- [ ] pack layout
- [ ] partition layout
- [ ] radial dendrogram
- [ ] radial tree layout
- [ ] sankey diagram
- [ ] treemap layout
- [ ] vertical dendrogram

### Validation
- [ ] example that displays each of the different plots with toy data
- [ ] build examples for win, linux, mac, android, ios, and web
