### ISSUE TITLE
Port of .py to .cpp

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#165]
### Description
Port of python implemented classes and workflows into C++ for seamless native integration and deployment

### Objectives
- [ ] port existing .py classes to C++
- [ ] port .py algorithms to C++

### Validation
- [ ] working tests ported from .py
- [ ] working examples ported from .py
