### ISSUE TITLE
EMG peak model

### ISSUE THREAD

**Issue by dmccloskey** [biosustain/OpenMS#67]
### Description
Calculate an EMG fit for the peak data points.  The peak area would be the area under the EMG curve.  The background would then be computed for a baseline_type_ of base_to_base as a rhomboid or vertical division as a rectangle similar to integration_type_ of trapezoid or simpson.  

### Objectives
- [x] fit a set of points to an EMG model
- [ ] calculate the peak area/height and background based on the EMG model fit

### Tests
- a toy peak (ideal peak)
- toy peak missing the top to simulate a saturated peak
- toy peak missing the side to simulate a cutoff peak
- a real saturated peak
- a real partial peak that was cutoff at the end of the chromatogram window
- a real saturated and cutoff peak

### References
[https://app.zenhub.com/files/101999003/4bf4c86a-fd07-4802-95c9-5ed31566a0c8/download](https://app.zenhub.com/files/101999003/4bf4c86a-fd07-4802-95c9-5ed31566a0c8/download)

**Comment by dmccloskey** [comment]
### Cutoff point interpolation steps
1. calculate the average sampling rate
2. inerpolate points using the average sampling rate until the delta height between the left and right is 0

**Comment by pcolaianni** [comment]
### TODO
- [x] write tests for every single helper method of the class
- [x] add tests for ideal peak case (no saturated, no cutoff)
- [x] test `Loss_function()` for different ranges of `z`
- [ ] Give reasoning for magic values within the code
- [ ] replace std::cout with LOG_DEBUG

**Comment by pcolaianni** [comment]
@dmccloskey Should we close this or do you plan to add / change things?
In those cases we could create new issues in future.
